export enum ROUTER {
  HOME = "/",
  AUTH = "/auth",
  LOGIN = "/auth/login",
  REGISTER = "/auth/register",
  DASHBOARD = "/dashboard",
  ACCOUNT = "/account",
  DECK = '/dashboard/deck',
  DECK_DETAIL = '/dashboard/deck/detail',
  DECK_DETAIL_NEW_FLASHCARD = '/dashboard/deck/detail/{deck_id}/new-flashcard',
  DECK_NEW = '/dashboard/deck/new',
  FLASHCARD = "/dashboard/flashcard",
  FLASHCARD_DETAIL = "/dashboard/flashcard/",
  FLASHCARD_NEW = "/dashboard/flashcard/new",
}
